# Generated by Django 3.2 on 2020-11-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
            ],
        ),
    ]
