# Generated by Django 3.1.2 on 2020-11-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201109_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
