# Generated by Django 3.2 on 2020-11-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201109_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido_multi',
            name='foto',
            field=models.ImageField(upload_to='FOTOS/'),
        ),
    ]
