# Generated by Django 3.1.2 on 2020-11-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mascota_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('Palmira', 'Palmira'), ('Cali', 'Cali'), ('Candelaria', 'Candelaria')], max_length=10),
        ),
    ]
