# Generated by Django 3.1.2 on 2020-11-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_mascota_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
