# Generated by Django 3.1.2 on 2020-11-22 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201122_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(null=True, upload_to='Mascotas/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='idfundacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.fundacion'),
        ),
    ]
