# Generated by Django 3.1.2 on 2020-11-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201122_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundacion',
            name='nombre_fund',
            field=models.CharField(max_length=255),
        ),
    ]
