# Generated by Django 3.2 on 2020-11-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adoptante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=255, verbose_name='email')),
                ('nombre', models.CharField(max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
