# Generated by Django 3.2 on 2020-11-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptante',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
