# Generated by Django 3.2 on 2020-11-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptantes', '0003_adoptante_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='correo',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email'),
        ),
    ]
