# Generated by Django 3.2 on 2020-10-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioFundacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('nombre_fund', models.CharField(max_length=30, unique=True)),
                ('info_fundacion', models.CharField(max_length=250)),
                ('ciudad', models.CharField(blank=True, choices=[('Palmira', 'Palmira')], max_length=10)),
            ],
        ),
    ]
