# Generated by Django 3.2 on 2020-10-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariofundacion',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuariofundacion',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuariofundacion',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('Palmira', 'Palmira'), ('Cali', 'Cali'), ('Candelaria', 'Candelaria')], max_length=10),
        ),
    ]
