# Generated by Django 3.2 on 2020-10-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0003_auto_20201027_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariofundacion',
            name='info_fundacion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuariofundacion',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
