# Generated by Django 3.2 on 2020-11-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0004_auto_20201027_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=255)),
                ('Tipo_Mascota', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], max_length=10)),
                ('Edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('Estado_esterilzacion', models.CharField(max_length=255)),
                ('Estado_salud', models.CharField(max_length=255)),
            ],
        ),
    ]
