# Generated by Django 3.2 on 2020-11-03 17:21

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0005_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='idfundacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fundacion.usuariofundacion'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='Estado_esterilzacion',
            field=models.CharField(choices=[('No_esterilizado', 'No Esterilizado'), ('Esterilizado', 'Esterilizado')], max_length=20),
        ),
        migrations.CreateModel(
            name='Contenido_Multi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenido', models.CharField(choices=[('Foto', 'Foto'), ('Video', 'Video')], max_length=10)),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('foto', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/fotos'), upload_to='')),
                ('id_mascota', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fundacion.mascota')),
            ],
        ),
    ]
