# Generated by Django 3.2 on 2020-11-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0006_auto_20201103_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariofundacion',
            name='correo',
            field=models.EmailField(max_length=255, verbose_name='email'),
        ),
    ]
