# Generated by Django 3.2 on 2020-11-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0007_alter_usuariofundacion_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariofundacion',
            name='id',
        ),
        migrations.AddField(
            model_name='usuariofundacion',
            name='ID_Fundacion',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
